# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/new-notebook',
                'doc_host': 'https://adamaslan.github.io',
                'git_url': 'https://github.com/adamaslan/new-notebook',
                'lib_path': 'new_notebook'},
  'syms': {'new_notebook.core': {'new_notebook.core.foo': ('core.html#foo', 'new_notebook/core.py')}}}
